spring:
  data:
    mongodb:
      username: root
      password: root
      database: user-service
      port: 27017
      host: localhost
      authentication-database: admin
server:
  port: 9011
jwt:
  secret-key: RandomKey


management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans

