spring:
  config:
    import:
    - "optional:configserver:http://localhost:8888"
    - "optional:file:.env[.properties]"
  profiles:
    active: development
  application:
    name: survey-service
  cloud:
    config:
      name: survey-service
